apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: "2023-03-13T16:31:41Z"
    generation: 6
    labels:
      cno-version: main
    name: democd
    namespace: demo-dev
    resourceVersion: "210284"
    uid: cfb54804-a5a2-4e6c-b683-f89100b3ed63
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: democd
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: democd
          cno-version: main
      spec:
        containers:
        - env:
          - name: test
            value: test
          image: docker.io/beopenit/democd@sha256:f7712eb9def22f3b624a6c95174e5106aba439a9ae5ca1a53a493a94db2fec5a
          imagePullPolicy: IfNotPresent
          name: container
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: "2023-03-13T16:36:07Z"
    creationTimestamp: "2023-03-13T16:29:44Z"
    generation: 5
    name: democd
    namespace: demo-dev
    resourceVersion: "204335"
    uid: 658d6687-ed33-486d-ba09-c666a7e736d2
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker.io/beopenit/democd:blue
      generation: 5
      importPolicy:
        importMode: Legacy
      name: blue
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: docker.io/beopenit/democd:red
      generation: 3
      importPolicy:
        importMode: Legacy
      name: red
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2023-03-13T16:52:25Z"
    name: democd
    namespace: demo-dev
    resourceVersion: "213265"
    uid: 28fda5e9-73ae-4941-af56-dfb1b47f28c5
  spec:
    clusterIP: 172.30.107.100
    clusterIPs:
    - 172.30.107.100
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: democd
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: "2023-03-13T16:53:53Z"
    name: democd
    namespace: demo-dev
    resourceVersion: "214045"
    uid: 3edcf7a0-1280-4c84-bd38-31221728caed
  spec:
    host: democd.testmigration.gocno.io
    port:
      targetPort: 8080
    to:
      kind: Service
      name: democd
      weight: 100
    wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
